# Generated by Django 5.1.6 on 2025-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_description_alter_course_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('a1', 'Elementary (A1)'), ('a2', 'Pre-Intermediate (A2)'), ('b1', 'Intermediate (B1)'), ('b1-b2', 'Upper-Intermediate (B1+)'), ('b2', 'Pre-Advanced (B2)')], default='a1', max_length=10),
        ),
    ]
