# Generated by Django 5.1.6 on 2025-03-12 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tinymceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_before', models.CharField(max_length=500)),
                ('text_after', models.CharField(blank=True, max_length=500, null=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_questions', to='main.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='FillInBlankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.fillinblankquestion')),
            ],
        ),
    ]
